---

env:
    DEST_BRANCH: "master"
    GOPATH: "/var/tmp/go"
    CIRRUS_WORKING_DIR: "${GOPATH}/src/github.com/containers/oci-seccomp-bpf-hook"
    GOSRC: "$CIRRUS_WORKING_DIR"
    SCRIPT_BASE: "./contrib/cirrus"
    CIRRUS_SHELL: "/bin/bash"
    IMAGE_PROJECT: "libpod-218412"
    HOME: "/root"  # not set by default
    GOCACHE: "${HOME}/.cache/go-build"


gating_task:

    # see bors.toml
    skip: $CIRRUS_BRANCH =~ ".*\.tmp"

    # Only run this on PRs, never during post-merge testing.  This is also required
    # for proper setting of EPOCH_TEST_COMMIT value, required by validation tools.
    only_if: $CIRRUS_BRANCH != $DEST_BRANCH

    env:
        CIRRUS_WORKING_DIR: "/usr/src/podman-py"
        GOPATH: "/go"
        GOSRC: "/go/src/github.com/containers/podman-py"
        PATH: "$PATH:/go/bin"

    # Runs within Cirrus's "community cluster"
    container:
        image: "quay.io/libpod/podmanpy_gating:master"
        cpu: 4
        memory: 12

    timeout_in: 20m

    gate_script:
        - make
        - go get github.com/vbatts/git-validation
        - make validate
        - make unittest


success_task:
    # This task is a required-pass in github settings,
    # it blocks PRs from merging if a depends_on task fails

    # see bors.toml
    skip: $CIRRUS_BRANCH =~ ".*\.tmp"

    only_if: $CIRRUS_BRANCH != $DEST_BRANCH

    # ignores any dependent task conditions
    depends_on:
        - gating

    container:
        image: "quay.io/libpod/podmanpy_gating:master"
        cpu: 1
        memory: 1
